- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.19.0
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
  - id: terraform_validate
  - id: terraform_tflint

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.8

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
  - id: flake8

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.720
#   hooks:
#   - id: mypy 
#     args: [--no-strict-optional, --ignore-missing-imports, ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-merge-conflict
    - id: check-added-large-files 
      args: ['--maxkb=5000']
    - id: check-yaml